"""
RFGN Real-Time Fraud Detection API

Application/API Integration
"""

from __future__ import annotations

import math
from contextlib import asynccontextmanager
from typing import Any, Dict, Optional

from fastapi import FastAPI, HTTPException
from pydantic import BaseModel, ConfigDict, Field, field_validator

from models.inference.inference_pipeline import (
    RFGNInferencePipeline,
)


# GLOBAL PIPELINE

pipeline: Optional[RFGNInferencePipeline] = None


# APPLICATION LIFESPAN

@asynccontextmanager
async def lifespan(app: FastAPI):

    global pipeline

    print("Starting RFGN inference service...")

    pipeline = RFGNInferencePipeline()

    print("RFGN inference service ready.")

    yield

    print("Stopping RFGN inference service...")

    pipeline = None


# FASTAPI APPLICATION

app = FastAPI(
    title="RFGN Fraud Detection API",
    description=(
        "Real-Time Fraud Detection API powered by "
        "Global GraphSAGE and DQN."
    ),
    version="1.0.0",
    lifespan=lifespan,
)


# REQUEST SCHEMA

class TransactionRequest(BaseModel):
    """
    Validated real-time transaction request.

    TransactionID is optional and will be generated by the
    transaction input module when omitted.

    isFraud is intentionally not part of this schema because
    the prediction API must not accept the ground-truth label.
    """

    model_config = ConfigDict(
        extra="forbid"
    )

    TransactionID: Optional[str] = Field(
        default=None,
        min_length=1,
        max_length=128,
        description=(
            "Optional transaction identifier. "
            "Generated automatically when omitted."
        ),
    )

    TransactionDT: float = Field(
        ...,
        description="Transaction timestamp.",
    )

    TransactionAmt: float = Field(
        ...,
        ge=0.0,
        description="Transaction amount.",
    )

    ProductCD: Optional[str] = Field(
        default=None,
        min_length=1,
        description="IEEE-CIS product category.",
    )

    card1: Optional[float] = None
    card2: Optional[float] = None
    card3: Optional[float] = None
    card5: Optional[float] = None

    addr1: Optional[float] = None
    addr2: Optional[float] = None

    P_emaildomain: Optional[str] = None
    R_emaildomain: Optional[str] = None

    DeviceInfo: Optional[str] = None

    # TRANSACTION ID VALIDATION

    @field_validator("TransactionID")
    @classmethod
    def validate_transaction_id(
        cls,
        value: Optional[str],
    ) -> Optional[str]:

        if value is None:
            return None

        value = value.strip()

        if not value:
            raise ValueError(
                "TransactionID cannot be empty."
            )

        return value

    # TIMESTAMP VALIDATION

    @field_validator("TransactionDT")
    @classmethod
    def validate_transaction_dt(
        cls,
        value: float,
    ) -> float:

        if not math.isfinite(value):
            raise ValueError(
                "TransactionDT must be a finite number."
            )

        if value < 0:
            raise ValueError(
                "TransactionDT cannot be negative."
            )

        return float(value)

    # AMOUNT VALIDATION

    @field_validator("TransactionAmt")
    @classmethod
    def validate_transaction_amount(
        cls,
        value: float,
    ) -> float:

        if not math.isfinite(value):
            raise ValueError(
                "TransactionAmt must be a finite number."
            )

        if value < 0:
            raise ValueError(
                "TransactionAmt cannot be negative."
            )

        return float(value)

    # PRODUCT VALIDATION

    @field_validator("ProductCD")
    @classmethod
    def validate_product(
        cls,
        value: Optional[str],
    ) -> Optional[str]:

        if value is None:
            return None

        value = value.strip()

        if not value:
            raise ValueError(
                "ProductCD cannot be empty."
            )

        return value

    # STRING FIELD CLEANING

    @field_validator(
        "P_emaildomain",
        "R_emaildomain",
        "DeviceInfo",
    )
    @classmethod
    def clean_string_fields(
        cls,
        value: Optional[str],
    ) -> Optional[str]:

        if value is None:
            return None

        value = value.strip()

        if not value:
            return None

        return value

    # NUMERIC FIELD VALIDATION

    @field_validator(
        "card1",
        "card2",
        "card3",
        "card5",
        "addr1",
        "addr2",
    )
    @classmethod
    def validate_optional_numeric(
        cls,
        value: Optional[float],
    ) -> Optional[float]:

        if value is None:
            return None

        if not math.isfinite(value):
            raise ValueError(
                "Numeric transaction fields must "
                "contain finite values."
            )

        return float(value)


# ROOT ENDPOINT

@app.get("/")
def root() -> Dict[str, Any]:

    return {
        "system": "RFGN",
        "service": "Fraud Detection API",
        "status": "online",
        "version": "1.0.0",
    }


# ============================================================
# HEALTH ENDPOINT
# ============================================================

@app.get("/health")
def health() -> Dict[str, Any]:

    if pipeline is None:

        raise HTTPException(
            status_code=503,
            detail={
                "system": "RFGN",
                "status": "initializing",
            },
        )

    try:

        pipeline_health = pipeline.health_check()

        return {
            "system": "RFGN",
            "status": "healthy",
            "pipeline": pipeline_health,
        }

    except Exception as exc:

        raise HTTPException(
            status_code=503,
            detail={
                "system": "RFGN",
                "status": "unhealthy",
                "error": str(exc),
            },
        )


# ============================================================
# SYSTEM STATUS ENDPOINT
# ============================================================

@app.get("/system/status")
def system_status() -> Dict[str, Any]:

    if pipeline is None:

        raise HTTPException(
            status_code=503,
            detail={
                "system": "RFGN",
                "status": "initializing",
            },
        )

    try:

        # IMPORTANT:
        # pipeline.health_check() already returns the complete
        # pipeline health dictionary.
        pipeline_health = pipeline.health_check()

        graph_builder = pipeline_health.get(
            "graph_builder",
            {},
        )

        feature_engineering = pipeline_health.get(
            "feature_engineering",
            {},
        )

        global_graphsage = pipeline_health.get(
            "global_graphsage",
            {},
        )

        dqn = pipeline_health.get(
            "dqn",
            {},
        )

        result_service = pipeline_health.get(
            "result_service",
            {},
        )

        database = result_service.get(
            "database",
            {},
        )

        summary = result_service.get(
            "summary",
            {},
        )

        # ----------------------------------------------------
        # COMPONENT STATUS CHECK
        # ----------------------------------------------------

        component_statuses = [
            pipeline_health.get("status"),
            graph_builder.get("status"),
            feature_engineering.get("status"),
            global_graphsage.get("status"),
            dqn.get("status"),
            result_service.get("status"),
            database.get("status"),
        ]

        operational = all(
            status in ("healthy", "ready")
            for status in component_statuses
        )

        overall_status = (
            "operational"
            if operational
            else "degraded"
        )

        # ----------------------------------------------------
        # SYSTEM STATUS RESPONSE
        # ----------------------------------------------------

        return {

            "system": "RFGN",

            "status": overall_status,

            "api": {
                "status": "online",
            },

            "database": {

                "status": database.get(
                    "status"
                ),

                "transactions": summary.get(
                    "transactions",
                    0,
                ),

                "detection_results": summary.get(
                    "detection_results",
                    0,
                ),

                "feedback": summary.get(
                    "feedback",
                    0,
                ),
            },

            "graph_builder": {

                "status": graph_builder.get(
                    "status"
                ),

                "raw_features": graph_builder.get(
                    "raw_feature_count"
                ),

                "shared_features": graph_builder.get(
                    "shared_feature_count"
                ),

                "normalization": graph_builder.get(
                    "normalization_method"
                ),
            },

            "feature_engineering": {

                "status": feature_engineering.get(
                    "status"
                ),

                "raw_features": feature_engineering.get(
                    "raw_feature_count"
                ),

                "shared_features": feature_engineering.get(
                    "shared_feature_count"
                ),

                "numeric_features": feature_engineering.get(
                    "numeric_feature_count"
                ),

                "categorical_features": feature_engineering.get(
                    "categorical_feature_count"
                ),
            },

            "models": {

                "graphsage": {

                    "status": global_graphsage.get(
                        "status"
                    ),

                    "input_features": global_graphsage.get(
                        "input_features"
                    ),

                    "hidden_features": global_graphsage.get(
                        "hidden_features"
                    ),

                    "output_classes": global_graphsage.get(
                        "output_classes"
                    ),

                    "parameters": global_graphsage.get(
                        "parameter_count"
                    ),

                    "eval_mode": global_graphsage.get(
                        "eval_mode"
                    ),
                },

                "dqn": {

                    "status": dqn.get(
                        "status"
                    ),

                    "actions": dqn.get(
                        "action_count"
                    ),

                    "state_size": dqn.get(
                        "state_size"
                    ),

                    "threshold": dqn.get(
                        "default_threshold"
                    ),

                    "minimum_threshold": dqn.get(
                        "minimum_threshold"
                    ),

                    "maximum_threshold": dqn.get(
                        "maximum_threshold"
                    ),
                },
            },

            "pipeline": {

                "status": pipeline_health.get(
                    "status"
                ),

                "input_features": global_graphsage.get(
                    "input_features"
                ),

                "decision_threshold": dqn.get(
                    "default_threshold"
                ),
            },
        }

    except Exception as exc:

        raise HTTPException(
            status_code=503,
            detail={
                "system": "RFGN",
                "status": "degraded",
                "error": str(exc),
            },
        )


# ============================================================
# PREDICT ENDPOINT
# ============================================================

@app.post("/predict")
def predict(
    request: TransactionRequest,
) -> Dict[str, Any]:

    if pipeline is None:

        raise HTTPException(
            status_code=503,
            detail={
                "status": "error",
                "message": (
                    "RFGN inference service "
                    "is not ready."
                ),
            },
        )

    try:

        transaction_data = request.model_dump(
            exclude_none=True
        )

        transaction_id = transaction_data.pop(
            "TransactionID",
            None,
        )

        result = pipeline.process_transaction(
            transaction_data=transaction_data,
            transaction_id=transaction_id,
            store_result=True,
        )

        return {

            "status": "success",

            "transaction_id": result[
                "transaction_id"
            ],

            "fraud_probability": result[
                "graphsage"
            ][
                "fraud_probability"
            ],

            "legitimate_probability": result[
                "graphsage"
            ][
                "legitimate_probability"
            ],

            "dqn_threshold": result[
                "dqn"
            ][
                "selected_threshold"
            ],

            "dqn_action": result[
                "dqn"
            ][
                "action"
            ],

            "decision": result[
                "final_decision"
            ][
                "decision"
            ],

            "predicted_class": result[
                "final_decision"
            ][
                "predicted_class"
            ],

            "model": "Global GraphSAGE + DQN",
        }

    except ValueError as exc:

        raise HTTPException(
            status_code=400,
            detail={
                "status": "error",
                "type": "validation_error",
                "message": str(exc),
            },
        )

    except Exception as exc:

        raise HTTPException(
            status_code=500,
            detail={
                "status": "error",
                "type": "inference_error",
                "message": str(exc),
            },
        )